version: '3.9'

services:
  app:
    container_name: fastapi
    build:
      context: .
      dockerfile: containers/fastapi/Dockerfile
    volumes:
      - ./application:/application
    ports:
      - "8000:8000"
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
